title: Nordlys Coders
contact_url: https://forms.gle/7H4QytSgSiPToiNb7
description: >- # this means to ignore newlines until "baseurl:"
  
url: https://nordlyscoders.github.io
baseurl: /website/
github_username: nordlyscoders

# Build settings
theme: minima
plugins: []

exclude:
  - Dockerfile
  - README.md
